column = {
    '1': 'No.',
    '2': 'Commission No.',
    '3': 'VIN No.',
    '4': 'Repair No.',
    '5': 'B/L no.',
    '6': 'Closing Date',
    '7': 'Incident date',
    '8': 'Damage Code01',
    '9': 'Damage Code02',
    '10': 'Damage Code03',
    '11': 'Damage Code04',
    '12': 'Damage Code05',
    '13': 'Damage Code06',
    '14': 'Damage Code07',
    '15': 'Damage Code08',
    '16': 'Damage Code09',
    '17': 'Damage Code10',
    '18': 'Sub Total',
    '19': 'Date of booking',
    '20': 'Reclamation date',
    '21': 'Audit type',
    '22': 'Claim Entry ID-Number',
    '23': 'CID',
    '24': 'Memo'
}